// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.32.1
// source: proto/files.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "files";

export interface UploadAvatarRequest {
  file: Uint8Array;
  oldFilename?: string | undefined;
}

export interface UploadAvatarResponse {
  filename: string;
}

export interface GetAvatarRequest {
  filename: string;
}

export interface GetAvatarResponse {
  file: Uint8Array;
}

export interface GenerateTransactionsExcelRequest {
  transactions: TransactionData[];
  bankId: string;
}

export interface TransactionData {
  id: string;
  amount: number;
  description: string;
  type: string;
  category?: string | undefined;
  depositType?: string | undefined;
  createdAt: number;
}

export interface GenerateTransactionsExcelResponse {
  file: Uint8Array;
  filename: string;
}

export const FILES_PACKAGE_NAME = "files";

export interface FilesServiceClient {
  uploadAvatar(request: UploadAvatarRequest): Observable<UploadAvatarResponse>;

  getAvatar(request: GetAvatarRequest): Observable<GetAvatarResponse>;

  generateTransactionsExcel(request: GenerateTransactionsExcelRequest): Observable<GenerateTransactionsExcelResponse>;
}

export interface FilesServiceController {
  uploadAvatar(
    request: UploadAvatarRequest,
  ): Promise<UploadAvatarResponse> | Observable<UploadAvatarResponse> | UploadAvatarResponse;

  getAvatar(request: GetAvatarRequest): Promise<GetAvatarResponse> | Observable<GetAvatarResponse> | GetAvatarResponse;

  generateTransactionsExcel(
    request: GenerateTransactionsExcelRequest,
  ):
    | Promise<GenerateTransactionsExcelResponse>
    | Observable<GenerateTransactionsExcelResponse>
    | GenerateTransactionsExcelResponse;
}

export function FilesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["uploadAvatar", "getAvatar", "generateTransactionsExcel"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FilesService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FilesService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FILES_SERVICE_NAME = "FilesService";
